Repository pagopa/pagopa-receipt-pdf-helpdesk, pull requests merged in 2023-11, with the labels that each got.

#5 fix deploy
  helm/Chart.lock
  helm/values-prod.yaml
Labels: patch

#3 [PRDP-238] API to modify ReceiptError status to REVIEWED
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewed.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/ReceiptCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/ReceiptError.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/model/ReceiptToReviewedRequest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewedTest.java
Labels: enhancement, minor, size/large

#4 feat: PRDP-237 Add recover api IO_ERROR_TO_NOTIFY and GENERATED status
  README.md
  openapi/openapi.json
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/ReceiptCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/CartItem.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/EventData.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/IOMessageData.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/ReasonError.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/Receipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/ReceiptMetadata.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/model/NotNotifiedRecoveryRequest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImplTest.java
  src/test/resources/logback-test.xml
Labels: enhancement, minor, size/large

#8 [fix] Improved toReviewed API adding receiptError status limit
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewed.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewedTest.java
Labels: size/small
