Repository pagopa/pagopa-receipt-pdf-helpdesk, pull requests merged in 2023-12, with the labels that each got.

#15 [PRDP-253] Refactor ReceiptToReviewed API
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewed.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewedTest.java
Labels: enhancement, minor

#17 [PRDP-256] feat: get Errors to review endpoint
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptError.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptErrorTest.java
Labels: minor

#13 [PRDP-255] feat: Refactored RegenerateReceiptPdf class
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: minor, size/small

#18 [PRDP-251] feat: Add get receipt API
  README.md
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptByOrganizationFiscalCodeAndIUV.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/BizEventCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/BizEventCosmosClientImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptByOrganizationFiscalCodeAndIUVTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptTest.java
Labels: enhancement, minor, size/large

#16 [feat] Added new fields name and surname to bizEvent User class
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/event/User.java
Labels: patch, size/small

#23 [PRDP-269] Updated openapi specs and API error responses
  openapi/openapi.json
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptByOrganizationFiscalCodeAndIUV.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptError.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptMassive.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassive.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdf.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptByOrganizationFiscalCodeAndIUVTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptErrorTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptMassiveTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassiveTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptQueueClientImplTest.java
Labels: patch, size/small

#21 [PRDP-268] feat: added scheduled for not notified
  .env.example
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassive.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptScheduled.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/RecoverNotNotifiedReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassiveTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptScheduledTest.java
Labels: minor

#24 fix: Helm
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small

#22 [PRDP-267] feat: Add timer trigger function for recovering failed receipt
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptMassive.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptScheduled.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassive.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/model/MassiveRecoverResult.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptErrorTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptScheduledTest.java
Labels: enhancement, minor, size/large

#25 chore: Add flag
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch

#26 Fix schedule env vars
  README.md
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptError.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/model/template/ReceiptPDFTemplate.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/BuildTemplateService.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/Aes256Utils.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/TemplateDataField.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptErrorTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: size/large, patch

#28 [PRDP-281] feat: add recovery of payer fiscal code from details
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptTest.java
Labels: patch, size/small

#29 [PRDP-284] feat: introduced limits on scheduled and massive recovery
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptScheduled.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
Labels: bug, patch, size/small

#30 fix env var
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#31 [feat] Added bizEvent status filter in query
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/BizEventCosmosClientImpl.java
Labels: patch, size/small

#35 [PRDP-288] feat: Update receipt eventData when missing on regen pdf
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImplTest.java
Labels: patch, size/small

#36 chore: Upd config processi helpdesk schedulati
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch

#32 chore: update number of days for massive recovery
  integration-test/src/step_definitions/common.js
Labels: size/small

#38 feat: Add limit on io error to notify massive recover
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/RecoverNotNotifiedReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassiveTest.java
Labels: patch, size/small

#39 feat: Add env to customize limit on io error to notify massive recover
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/RecoverNotNotifiedReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassiveTest.java
Labels: patch, size/small

#40 fix: Limit to not notified massive recover
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/RecoverNotNotifiedReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassiveTest.java
Labels: patch, size/small

#42 [PRDP-302] feat: add recover message to helpdesk
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/features/receipt_pdf_helpdesk.feature
  integration-test/src/script/teardown_script.js
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_helpdesk_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptMessage.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/ReceiptCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/IOMessage.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/exception/IoMessageNotFoundException.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/ReceiptCosmosService.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptMessageTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImplTest.java
Labels: minor, size/large

#43 [PRDP-302] feat: fix api_helpdesk_client.js
  integration-test/src/step_definitions/api_helpdesk_client.js
Labels: patch, size/small

#44 [PRDP-302] chore: updated openapi.json
  openapi/openapi.json
Labels: documentation, size/small, skip

#45 [PRDP-304] feat: Updated checks for anonym debtor management
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: patch, size/small
