Repository pagopa/pagopa-receipt-pdf-helpdesk, pull requests merged in 2024-01, with the labels that each got.

#46 fix: getReceiptMessage integration tests
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/receipt_pdf_helpdesk.feature
  integration-test/src/step_definitions/receipt_pdf_helpdesk_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
Labels: size/small, skip

#47 [PRDP-307] feat: API getCart
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/GetCart.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/ReceiptCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/cart/CartForReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/cart/CartStatusType.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/exception/CartNotFoundException.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/ReceiptCosmosService.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetCartTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImplTest.java
Labels: minor, size/large

#33 [PRDP-286] Added isCart field to Receipt
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/Receipt.java
Labels: patch, size/small

#49 [PRDP-289] feat: add failed cart recovery
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewed.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCart.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartMassive.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartScheduled.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/BizEventCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/CartReceiptsCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/BizEventCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/CartReceiptsCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/cart/CartForReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/model/MassiveRecoverCartResult.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/BizEventToReceiptService.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/BuildTemplateService.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/GenerateReceiptPdfService.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/GenerateReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewedTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartMassiveScheduledTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartMassiveTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/CartReceiptsCosmosClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtilsTest.java
Labels: minor, size/large

#51 fix: grand total amount format
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/ReceiptToReviewedTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptTest.java
Labels: patch, size/small

#52 fix: grand total amount format in template generation
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImplTest.java
Labels: patch, size/small

#50 [PRDP-291] feat: Add integration test for cart API
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/receipt_pdf_helpdesk.feature
  integration-test/src/step_definitions/api_helpdesk_client.js
  integration-test/src/step_definitions/biz_events_datastore_client.js
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_helpdesk_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCart.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartMassive.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartScheduled.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/CartReceiptsCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/ReceiptCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/CartReceiptsCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/cart/CartForReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/entity/receipt/Receipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/client/impl/ReceiptCosmosClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/ReceiptCosmosServiceImplTest.java
Labels: size/large, patch

#53 Upd uat and prod cfg + fix typo
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/RecoverNotNotifiedReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptByOrganizationFiscalCodeAndIUVTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/GetReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartMassiveScheduledTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartMassiveTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptMassiveTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptScheduledTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverNotNotifiedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: patch, size/small

#57 fix: prod
  helm/values-prod.yaml
Labels: size/small

#54 [PRDP-324] feat: origin check when setting payer fiscal code on receipt
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCart.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RegenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtilsTest.java
Labels: patch, size/small

#59 fix: UAT helm
  helm/values-uat.yaml
Labels: skip

#60 feat: add cf checks to helpdesk
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedCartTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptMassiveTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptScheduledTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/RecoverFailedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtilsTest.java
Labels: patch, size/small

#63 [PRDP-337] fix: Inverted payer tax code checks
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
Labels: bug, patch, size/small

#61 [PRDP-333] fix: Amount format
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
Labels: bug, patch, size/small

#64 [fix] Fixed payer fiscal code check when discarding events
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
Labels: bug, patch, size/small

#65 [fix] Added check on transaction origin when checking payer fiscal code
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
Labels: bug, patch, size/small

#66 [PRDP-335] Introduced remittance information check with regex against unwanted strings
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/utils/BizEventToReceiptUtilsTest.java
Labels: bug, patch

#67 chore: Fix cfg helm env
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small
