Repository pagopa/pagopa-receipt-pdf-helpdesk, pull requests merged in 2025-06, with the labels that each got.

#89 chore: Disable crons helpdesk
  helm/values-prod.yaml
Labels: patch, size/small

#90 [PIDM-352] fix: Payment method name mapping
  helm/template/configmaps.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/service/impl/BuildTemplateServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/helpdesk/util/ObjectMapperUtils.java
  src/test/resources/biz-events/bizEventGuest.json
  src/test/resources/psp_config_file.json
Labels: size/large, patch

#93 fix: [PIDM-731] Added payment method config map to helm
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: bug, patch, size/small

#94 feat: [PIDM-733] Add payment method Klarna
  helm/template/configmaps.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small
